
// This file has been generated by the GUI designer. Do not modify.
namespace LongoMatch.Gui.Dialog
{
	public partial class SubCategoryTagsEditor
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.Table table1;

		private global::Gtk.CheckButton fastcheckbutton;

		private global::Gtk.Label label1;

		private global::Gtk.CheckButton multicheckbutton;

		private global::Gtk.Entry nameentry;

		private global::Gtk.Frame frame1;

		private global::Gtk.Alignment GtkAlignment2;

		private global::Gtk.VBox vbox3;

		private global::Gtk.ScrolledWindow scrolledwindow1;

		private global::Gtk.VBox tagsbox;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Entry tagentry;

		private global::Gtk.Button addtagbutton;

		private global::Gtk.Label GtkLabel4;

		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LongoMatch.Gui.Dialog.SubCategoryTagsEditor
			this.Name = "LongoMatch.Gui.Dialog.SubCategoryTagsEditor";
			this.Title = global::Mono.Unix.Catalog.GetString ("Edit subcategory tags");
			this.Icon = global::Gdk.Pixbuf.LoadFromResource ("longomatch.png");
			this.WindowPosition = ((global::Gtk.WindowPosition)(1));
			this.Modal = true;
			this.Gravity = ((global::Gdk.Gravity)(5));
			this.SkipPagerHint = true;
			this.SkipTaskbarHint = true;
			// Internal child LongoMatch.Gui.Dialog.SubCategoryTagsEditor.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.fastcheckbutton = new global::Gtk.CheckButton ();
			this.fastcheckbutton.TooltipMarkup = "When this option is selected, the subcategory can be tagged right after creating a new play";
			this.fastcheckbutton.CanFocus = true;
			this.fastcheckbutton.Name = "fastcheckbutton";
			this.fastcheckbutton.Label = global::Mono.Unix.Catalog.GetString ("Quick tag");
			this.fastcheckbutton.Active = true;
			this.fastcheckbutton.DrawIndicator = true;
			this.fastcheckbutton.UseUnderline = true;
			this.table1.Add (this.fastcheckbutton);
			global::Gtk.Table.TableChild w2 = ((global::Gtk.Table.TableChild)(this.table1[this.fastcheckbutton]));
			w2.TopAttach = ((uint)(1));
			w2.BottomAttach = ((uint)(2));
			w2.LeftAttach = ((uint)(1));
			w2.RightAttach = ((uint)(2));
			w2.XOptions = ((global::Gtk.AttachOptions)(4));
			w2.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Subcategory name:");
			this.table1.Add (this.label1);
			global::Gtk.Table.TableChild w3 = ((global::Gtk.Table.TableChild)(this.table1[this.label1]));
			w3.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.multicheckbutton = new global::Gtk.CheckButton ();
			this.multicheckbutton.TooltipMarkup = "This options allows you to select multiple tags instead of just one";
			this.multicheckbutton.CanFocus = true;
			this.multicheckbutton.Name = "multicheckbutton";
			this.multicheckbutton.Label = global::Mono.Unix.Catalog.GetString ("Allow multiple selections");
			this.multicheckbutton.Active = true;
			this.multicheckbutton.DrawIndicator = true;
			this.multicheckbutton.UseUnderline = true;
			this.table1.Add (this.multicheckbutton);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1[this.multicheckbutton]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.nameentry = new global::Gtk.Entry ();
			this.nameentry.CanFocus = true;
			this.nameentry.Name = "nameentry";
			this.nameentry.Text = global::Mono.Unix.Catalog.GetString ("Goal type");
			this.nameentry.IsEditable = true;
			this.nameentry.InvisibleChar = '•';
			this.table1.Add (this.nameentry);
			global::Gtk.Table.TableChild w5 = ((global::Gtk.Table.TableChild)(this.table1[this.nameentry]));
			w5.LeftAttach = ((uint)(1));
			w5.RightAttach = ((uint)(2));
			w5.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox2.Add (this.table1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.table1]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment2 = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
			this.GtkAlignment2.Name = "GtkAlignment2";
			this.GtkAlignment2.LeftPadding = ((uint)(12));
			// Container child GtkAlignment2.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow1.CanFocus = true;
			this.scrolledwindow1.Name = "scrolledwindow1";
			// Container child scrolledwindow1.Gtk.Container+ContainerChild
			global::Gtk.Viewport w7 = new global::Gtk.Viewport ();
			w7.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.tagsbox = new global::Gtk.VBox ();
			this.tagsbox.Name = "tagsbox";
			this.tagsbox.Spacing = 6;
			w7.Add (this.tagsbox);
			this.scrolledwindow1.Add (w7);
			this.vbox3.Add (this.scrolledwindow1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.scrolledwindow1]));
			w10.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.tagentry = new global::Gtk.Entry ();
			this.tagentry.CanFocus = true;
			this.tagentry.Name = "tagentry";
			this.tagentry.Text = global::Mono.Unix.Catalog.GetString ("Penalty");
			this.tagentry.IsEditable = true;
			this.tagentry.InvisibleChar = '•';
			this.hbox1.Add (this.tagentry);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.tagentry]));
			w11.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.addtagbutton = new global::Gtk.Button ();
			this.addtagbutton.CanFocus = true;
			this.addtagbutton.Name = "addtagbutton";
			this.addtagbutton.UseUnderline = true;
			// Container child addtagbutton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w12 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w13 = new global::Gtk.HBox ();
			w13.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w14 = new global::Gtk.Image ();
			w14.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			w13.Add (w14);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w16 = new global::Gtk.Label ();
			w16.LabelProp = global::Mono.Unix.Catalog.GetString ("Add tag");
			w16.UseUnderline = true;
			w13.Add (w16);
			w12.Add (w13);
			this.addtagbutton.Add (w12);
			this.hbox1.Add (this.addtagbutton);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.addtagbutton]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			this.vbox3.Add (this.hbox1);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.hbox1]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			this.GtkAlignment2.Add (this.vbox3);
			this.frame1.Add (this.GtkAlignment2);
			this.GtkLabel4 = new global::Gtk.Label ();
			this.GtkLabel4.Name = "GtkLabel4";
			this.GtkLabel4.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>Tags</b>");
			this.GtkLabel4.UseMarkup = true;
			this.frame1.LabelWidget = this.GtkLabel4;
			this.vbox2.Add (this.frame1);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.frame1]));
			w24.Position = 1;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(w1[this.vbox2]));
			w25.Position = 0;
			// Internal child LongoMatch.Gui.Dialog.SubCategoryTagsEditor.ActionArea
			global::Gtk.HButtonBox w26 = this.ActionArea;
			w26.Name = "dialog1_ActionArea";
			w26.Spacing = 10;
			w26.BorderWidth = ((uint)(5));
			w26.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w27 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w26[this.buttonOk]));
			w27.Expand = false;
			w27.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 326;
			this.DefaultHeight = 304;
			this.Show ();
		}
	}
}
