// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace LongoMatch.Video {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public enum GstPlayerMetadataType {

		Title,
		Artist,
		Year,
		Album,
		Duration,
		TrackNumber,
		HasVideo,
		DimensionX,
		DimensionY,
		VideoBitrate,
		VideoCodec,
		Fps,
		HasAudio,
		AudioBitrate,
		AudioCodec,
		AudioSampleRate,
		AudioChannels,
	}
#endregion
}
