#!/usr/bin/env python

VERSION = "0.0.1"
VERSION_MAJOR_MINOR = ".".join(VERSION.split(".")[0:2])
APPNAME = "msi-extractor"

srcdir = '.'
blddir = '_build_'

def set_options(opt):
    opt.tool_options('compiler_cc')

def configure(conf):
    conf.check_tool('compiler_cc')
    conf.check_tool('checks')

    conf.check_pkg('glib-2.0', destvar='GLIB', vnum='2.10.0')
    conf.check_pkg('gobject-2.0', destvar='GOBJECT', vnum='2.10.0')
    conf.check_pkg('libgsf-1', destvar='LIBGSF', vnum='1.14.0')

    conf.define('PACKAGE', APPNAME)
    conf.define('PACKAGE_NAME', APPNAME)
    conf.define('PACKAGE_STRING', APPNAME + '-' + VERSION)
    conf.define('PACKAGE_VERSION', APPNAME + '-' + VERSION)

    conf.define('VERSION', VERSION)
    conf.define('VERSION_MAJOR_MINOR', VERSION_MAJOR_MINOR)

def build(bld):
    prog = bld.create_obj('cc', 'program')
    prog.name = 'msi-extractor.program'
    prog.target = 'msi-extractor'
    prog.source = 'msi-extractor.c'
    prog.uselib = 'LIBGSF'

