// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace LongoMatch {

	using System;

	public delegate void OutChangedHandler(object o, OutChangedArgs args);

	public class OutChangedArgs : GLib.SignalArgs {
		public double Val{
			get {
				return (double) Args[0];
			}
		}

	}
}
