prefix=/usr/local
exec_prefix=${prefix}
bindir=${exec_prefix}/bin
libdir=${exec_prefix}/lib
includedir=${prefix}/include
ARCH=X86
SYS=MINGW
CC=gcc
CFLAGS=-O1 -g  -Wall -I. -DHAVE_MMX -DARCH_X86 -DSYS_MINGW -DHAVE_PTHREAD
ALTIVECFLAGS=
LDFLAGS= -lpthread -lvfw32
AR=ar
RANLIB=ranlib
STRIP=strip
AS=yasm
ASFLAGS= -O2 -f win32 -DPREFIX
EXE=.exe
VIS=no
HAVE_GETOPT_LONG=1
DEVNULL=NUL
