// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace LongoMatch {

	using System;
	using System.Runtime.InteropServices;

#region Autogenerated code
	public enum BvwAspectRatio {

		Auto,
		Square = 1,
		Fourbythree = 2,
		Anamorphic = 3,
		Dvb = 4,
	}
#endregion
}
