// This file was generated by the Gtk# code generator.
// Any changes made will be lost if regenerated.

namespace LongoMatch.Video.Capturer {

	using System;

	public delegate void ErrorHandler(object o, ErrorArgs args);

	public class ErrorArgs : GLib.SignalArgs {
		public string Message{
			get {
				return (string) Args[0];
			}
		}

	}
}
