// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LongoMatch {
    
    
    public partial class TimeLine {
        
        private Gtk.VBox vbox2;
        
        private Gtk.HBox hbox1;
        
        private LongoMatch.TimeScale timescale1;
        
        private Gtk.Button zoominbutton;
        
        private Gtk.Button zoomoutbutton;
        
        private LongoMatch.TimePrecisionAdjustWidget timeprecisionadjustwidget1;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget LongoMatch.TimeLine
            Stetic.BinContainer.Attach(this);
            this.Name = "LongoMatch.TimeLine";
            // Container child LongoMatch.TimeLine.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            // Container child hbox1.Gtk.Box+BoxChild
            this.timescale1 = new LongoMatch.TimeScale();
            this.timescale1.Events = ((Gdk.EventMask)(256));
            this.timescale1.Name = "timescale1";
            this.hbox1.Add(this.timescale1);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox1[this.timescale1]));
            w1.Position = 0;
            // Container child hbox1.Gtk.Box+BoxChild
            this.zoominbutton = new Gtk.Button();
            this.zoominbutton.CanFocus = true;
            this.zoominbutton.Name = "zoominbutton";
            this.zoominbutton.UseUnderline = true;
            // Container child zoominbutton.Gtk.Container+ContainerChild
            Gtk.Alignment w2 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w3 = new Gtk.HBox();
            w3.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w4 = new Gtk.Image();
            w4.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-zoom-in", Gtk.IconSize.SmallToolbar, 18);
            w3.Add(w4);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w6 = new Gtk.Label();
            w6.LabelProp = "";
            w3.Add(w6);
            w2.Add(w3);
            this.zoominbutton.Add(w2);
            this.hbox1.Add(this.zoominbutton);
            Gtk.Box.BoxChild w10 = ((Gtk.Box.BoxChild)(this.hbox1[this.zoominbutton]));
            w10.Position = 1;
            w10.Expand = false;
            w10.Fill = false;
            // Container child hbox1.Gtk.Box+BoxChild
            this.zoomoutbutton = new Gtk.Button();
            this.zoomoutbutton.CanFocus = true;
            this.zoomoutbutton.Name = "zoomoutbutton";
            this.zoomoutbutton.UseUnderline = true;
            // Container child zoomoutbutton.Gtk.Container+ContainerChild
            Gtk.Alignment w11 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w12 = new Gtk.HBox();
            w12.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w13 = new Gtk.Image();
            w13.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-zoom-out", Gtk.IconSize.SmallToolbar, 18);
            w12.Add(w13);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w15 = new Gtk.Label();
            w15.LabelProp = "";
            w12.Add(w15);
            w11.Add(w12);
            this.zoomoutbutton.Add(w11);
            this.hbox1.Add(this.zoomoutbutton);
            Gtk.Box.BoxChild w19 = ((Gtk.Box.BoxChild)(this.hbox1[this.zoomoutbutton]));
            w19.Position = 2;
            w19.Expand = false;
            w19.Fill = false;
            this.vbox2.Add(this.hbox1);
            Gtk.Box.BoxChild w20 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
            w20.Position = 0;
            w20.Expand = false;
            w20.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.timeprecisionadjustwidget1 = new LongoMatch.TimePrecisionAdjustWidget();
            this.timeprecisionadjustwidget1.Events = ((Gdk.EventMask)(256));
            this.timeprecisionadjustwidget1.Name = "timeprecisionadjustwidget1";
            this.vbox2.Add(this.timeprecisionadjustwidget1);
            Gtk.Box.BoxChild w21 = ((Gtk.Box.BoxChild)(this.vbox2[this.timeprecisionadjustwidget1]));
            w21.Position = 1;
            w21.Expand = false;
            w21.Fill = false;
            this.Add(this.vbox2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.timescale1.PosValueChanged += new LongoMatch.PosValueChangedHandler(this.OnTimescale1PosValueChanged);
            this.timescale1.StartValueChanged += new LongoMatch.StartValueChangedHandler(this.OnTimescale1StartValueChanged);
            this.timescale1.StopValueChanged += new LongoMatch.StopValueChangedHandler(this.OnTimescale1StopValueChanged);
            this.zoominbutton.Clicked += new System.EventHandler(this.OnZoominbuttonClicked);
            this.zoomoutbutton.Clicked += new System.EventHandler(this.OnZoomoutbuttonClicked);
        }
    }
}
