// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LongoMatch {
    
    
    public partial class PlayListWidget {
        
        private Gtk.VBox vbox2;
        
        private Gtk.ScrolledWindow scrolledwindow1;
        
        private LongoMatch.PlayListTreeView playlisttreeview1;
        
        private Gtk.HBox hbox2;
        
        private Gtk.Button openbutton;
        
        private Gtk.Button savebutton;
        
        private Gtk.Button upbutton;
        
        private Gtk.Button downbutton;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget LongoMatch.PlayListWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "LongoMatch.PlayListWidget";
            // Container child LongoMatch.PlayListWidget.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.scrolledwindow1 = new Gtk.ScrolledWindow();
            this.scrolledwindow1.CanFocus = true;
            this.scrolledwindow1.Name = "scrolledwindow1";
            this.scrolledwindow1.ShadowType = ((Gtk.ShadowType)(1));
            // Container child scrolledwindow1.Gtk.Container+ContainerChild
            this.playlisttreeview1 = new LongoMatch.PlayListTreeView();
            this.playlisttreeview1.CanFocus = true;
            this.playlisttreeview1.Name = "playlisttreeview1";
            this.playlisttreeview1.Reorderable = true;
            this.playlisttreeview1.HeadersClickable = true;
            this.scrolledwindow1.Add(this.playlisttreeview1);
            this.vbox2.Add(this.scrolledwindow1);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox2[this.scrolledwindow1]));
            w2.Position = 0;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Homogeneous = true;
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.openbutton = new Gtk.Button();
            this.openbutton.CanFocus = true;
            this.openbutton.Name = "openbutton";
            this.openbutton.UseUnderline = true;
            // Container child openbutton.Gtk.Container+ContainerChild
            Gtk.Alignment w3 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w4 = new Gtk.HBox();
            w4.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w5 = new Gtk.Image();
            w5.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-open", Gtk.IconSize.Button, 20);
            w4.Add(w5);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w7 = new Gtk.Label();
            w7.LabelProp = "";
            w4.Add(w7);
            w3.Add(w4);
            this.openbutton.Add(w3);
            this.hbox2.Add(this.openbutton);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.hbox2[this.openbutton]));
            w11.Position = 0;
            // Container child hbox2.Gtk.Box+BoxChild
            this.savebutton = new Gtk.Button();
            this.savebutton.CanFocus = true;
            this.savebutton.Name = "savebutton";
            this.savebutton.UseUnderline = true;
            // Container child savebutton.Gtk.Container+ContainerChild
            Gtk.Alignment w12 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w13 = new Gtk.HBox();
            w13.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w14 = new Gtk.Image();
            w14.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-save", Gtk.IconSize.Button, 20);
            w13.Add(w14);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w16 = new Gtk.Label();
            w16.LabelProp = "";
            w13.Add(w16);
            w12.Add(w13);
            this.savebutton.Add(w12);
            this.hbox2.Add(this.savebutton);
            Gtk.Box.BoxChild w20 = ((Gtk.Box.BoxChild)(this.hbox2[this.savebutton]));
            w20.Position = 1;
            // Container child hbox2.Gtk.Box+BoxChild
            this.upbutton = new Gtk.Button();
            this.upbutton.CanFocus = true;
            this.upbutton.Name = "upbutton";
            this.upbutton.UseUnderline = true;
            // Container child upbutton.Gtk.Container+ContainerChild
            Gtk.Alignment w21 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w22 = new Gtk.HBox();
            w22.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w23 = new Gtk.Image();
            w23.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-go-up", Gtk.IconSize.Button, 20);
            w22.Add(w23);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w25 = new Gtk.Label();
            w25.LabelProp = "";
            w22.Add(w25);
            w21.Add(w22);
            this.upbutton.Add(w21);
            this.hbox2.Add(this.upbutton);
            Gtk.Box.BoxChild w29 = ((Gtk.Box.BoxChild)(this.hbox2[this.upbutton]));
            w29.Position = 2;
            // Container child hbox2.Gtk.Box+BoxChild
            this.downbutton = new Gtk.Button();
            this.downbutton.CanFocus = true;
            this.downbutton.Name = "downbutton";
            this.downbutton.UseUnderline = true;
            // Container child downbutton.Gtk.Container+ContainerChild
            Gtk.Alignment w30 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w31 = new Gtk.HBox();
            w31.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w32 = new Gtk.Image();
            w32.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-go-down", Gtk.IconSize.Button, 20);
            w31.Add(w32);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w34 = new Gtk.Label();
            w34.LabelProp = "";
            w31.Add(w34);
            w30.Add(w31);
            this.downbutton.Add(w30);
            this.hbox2.Add(this.downbutton);
            Gtk.Box.BoxChild w38 = ((Gtk.Box.BoxChild)(this.hbox2[this.downbutton]));
            w38.Position = 3;
            this.vbox2.Add(this.hbox2);
            Gtk.Box.BoxChild w39 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
            w39.Position = 1;
            w39.Expand = false;
            w39.Fill = false;
            this.Add(this.vbox2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.playlisttreeview1.RowActivated += new Gtk.RowActivatedHandler(this.OnPlaylisttreeview1RowActivated);
        }
    }
}
