// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LongoMatch {
    
    
    public partial class CapturePropertiesWidget {
        
        private Gtk.Expander expander1;
        
        private Gtk.Label GtkLabel;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget LongoMatch.CapturePropertiesWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "LongoMatch.CapturePropertiesWidget";
            // Container child LongoMatch.CapturePropertiesWidget.Gtk.Container+ContainerChild
            this.expander1 = new Gtk.Expander(null);
            this.expander1.CanFocus = true;
            this.expander1.Name = "expander1";
            this.expander1.Expanded = true;
            this.GtkLabel = new Gtk.Label();
            this.GtkLabel.Name = "GtkLabel";
            this.GtkLabel.LabelProp = Mono.Unix.Catalog.GetString("expander1");
            this.GtkLabel.UseUnderline = true;
            this.expander1.LabelWidget = this.GtkLabel;
            this.Add(this.expander1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
        }
    }
}
