// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LongoMatch.Gui.Component {


	public partial class DrawingWidget {

		private Gtk.ScrolledWindow GtkScrolledWindow;

		private Gtk.DrawingArea drawingarea;

		protected virtual void Build() {
			Stetic.Gui.Initialize(this);
			// Widget LongoMatch.Gui.Component.DrawingWidget
			Stetic.BinContainer.Attach(this);
			this.Name = "LongoMatch.Gui.Component.DrawingWidget";
			// Container child LongoMatch.Gui.Component.DrawingWidget.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			Gtk.Viewport w1 = new Gtk.Viewport();
			w1.ShadowType = ((Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.drawingarea = new Gtk.DrawingArea();
			this.drawingarea.Events = ((Gdk.EventMask)(784));
			this.drawingarea.Name = "drawingarea";
			w1.Add(this.drawingarea);
			this.GtkScrolledWindow.Add(w1);
			this.Add(this.GtkScrolledWindow);
			if ((this.Child != null)) {
				this.Child.ShowAll();
			}
			this.Hide();
			this.drawingarea.ExposeEvent += new Gtk.ExposeEventHandler(this.OnDrawingareaExposeEvent);
			this.drawingarea.ButtonPressEvent += new Gtk.ButtonPressEventHandler(this.OnDrawingareaButtonPressEvent);
			this.drawingarea.ButtonReleaseEvent += new Gtk.ButtonReleaseEventHandler(this.OnDrawingareaButtonReleaseEvent);
			this.drawingarea.MotionNotifyEvent += new Gtk.MotionNotifyEventHandler(this.OnDrawingareaMotionNotifyEvent);
			this.drawingarea.SizeAllocated += new Gtk.SizeAllocatedHandler(this.OnDrawingareaSizeAllocated);
			this.drawingarea.ConfigureEvent += new Gtk.ConfigureEventHandler(this.OnDrawingareaConfigureEvent);
		}
	}
}
