
// This file has been generated by the GUI designer. Do not modify.
namespace LongoMatch.Gui.Component
{
	public partial class TemplatesEditorBase
	{
		private global::Gtk.HBox hbox1;

		private global::Gtk.ScrolledWindow scrolledwindow2;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Button newprevbutton;

		private global::Gtk.Button newafterbutton;

		private global::Gtk.Button removebutton;

		private global::Gtk.Button editbutton;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.Button exportbutton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LongoMatch.Gui.Component.TemplatesEditorBase
			global::Stetic.BinContainer.Attach (this);
			this.Name = "LongoMatch.Gui.Component.TemplatesEditorBase";
			// Container child LongoMatch.Gui.Component.TemplatesEditorBase.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.scrolledwindow2 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow2.CanFocus = true;
			this.scrolledwindow2.Name = "scrolledwindow2";
			this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			this.hbox1.Add (this.scrolledwindow2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.scrolledwindow2]));
			w1.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.newprevbutton = new global::Gtk.Button ();
			this.newprevbutton.TooltipMarkup = "Insert a new category before the selected one";
			this.newprevbutton.Sensitive = false;
			this.newprevbutton.CanFocus = true;
			this.newprevbutton.Name = "newprevbutton";
			this.newprevbutton.UseUnderline = true;
			// Container child newprevbutton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w2 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w3 = new global::Gtk.HBox ();
			w3.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w4 = new global::Gtk.Image ();
			w4.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-goto-top", global::Gtk.IconSize.Menu);
			w3.Add (w4);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w6 = new global::Gtk.Label ();
			w6.LabelProp = global::Mono.Unix.Catalog.GetString ("New Before");
			w6.UseUnderline = true;
			w3.Add (w6);
			w2.Add (w3);
			this.newprevbutton.Add (w2);
			this.vbox2.Add (this.newprevbutton);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.newprevbutton]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.newafterbutton = new global::Gtk.Button ();
			this.newafterbutton.TooltipMarkup = "Insert a new category after the selected one";
			this.newafterbutton.Sensitive = false;
			this.newafterbutton.CanFocus = true;
			this.newafterbutton.Name = "newafterbutton";
			this.newafterbutton.UseUnderline = true;
			// Container child newafterbutton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w11 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w12 = new global::Gtk.HBox ();
			w12.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w13 = new global::Gtk.Image ();
			w13.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-goto-bottom", global::Gtk.IconSize.Menu);
			w12.Add (w13);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w15 = new global::Gtk.Label ();
			w15.LabelProp = global::Mono.Unix.Catalog.GetString ("New After");
			w15.UseUnderline = true;
			w12.Add (w15);
			w11.Add (w12);
			this.newafterbutton.Add (w11);
			this.vbox2.Add (this.newafterbutton);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.newafterbutton]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.removebutton = new global::Gtk.Button ();
			this.removebutton.TooltipMarkup = "Remove the selected category";
			this.removebutton.Sensitive = false;
			this.removebutton.CanFocus = true;
			this.removebutton.Name = "removebutton";
			this.removebutton.UseUnderline = true;
			// Container child removebutton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w20 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w21 = new global::Gtk.HBox ();
			w21.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w22 = new global::Gtk.Image ();
			w22.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-remove", global::Gtk.IconSize.Menu);
			w21.Add (w22);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w24 = new global::Gtk.Label ();
			w24.LabelProp = global::Mono.Unix.Catalog.GetString ("Remove");
			w24.UseUnderline = true;
			w21.Add (w24);
			w20.Add (w21);
			this.removebutton.Add (w20);
			this.vbox2.Add (this.removebutton);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.removebutton]));
			w28.Position = 2;
			w28.Expand = false;
			w28.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.editbutton = new global::Gtk.Button ();
			this.editbutton.TooltipMarkup = "Edit the selected category";
			this.editbutton.Sensitive = false;
			this.editbutton.CanFocus = true;
			this.editbutton.Name = "editbutton";
			this.editbutton.UseUnderline = true;
			// Container child editbutton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w29 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w30 = new global::Gtk.HBox ();
			w30.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w31 = new global::Gtk.Image ();
			w31.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.Menu);
			w30.Add (w31);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w33 = new global::Gtk.Label ();
			w33.LabelProp = global::Mono.Unix.Catalog.GetString ("Edit");
			w33.UseUnderline = true;
			w30.Add (w33);
			w29.Add (w30);
			this.editbutton.Add (w29);
			this.vbox2.Add (this.editbutton);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.editbutton]));
			w37.Position = 3;
			w37.Expand = false;
			w37.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox2.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hseparator1]));
			w38.Position = 4;
			w38.Expand = false;
			w38.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.exportbutton = new global::Gtk.Button ();
			this.exportbutton.TooltipMarkup = "Export the template to a file";
			this.exportbutton.CanFocus = true;
			this.exportbutton.Name = "exportbutton";
			this.exportbutton.UseUnderline = true;
			// Container child exportbutton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w39 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w40 = new global::Gtk.HBox ();
			w40.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w41 = new global::Gtk.Image ();
			w41.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-save-as", global::Gtk.IconSize.Menu);
			w40.Add (w41);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w43 = new global::Gtk.Label ();
			w43.LabelProp = global::Mono.Unix.Catalog.GetString ("Export");
			w43.UseUnderline = true;
			w40.Add (w43);
			w39.Add (w40);
			this.exportbutton.Add (w39);
			this.vbox2.Add (this.exportbutton);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.exportbutton]));
			w47.PackType = ((global::Gtk.PackType)(1));
			w47.Position = 5;
			w47.Expand = false;
			w47.Fill = false;
			this.hbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
			w48.Position = 1;
			w48.Expand = false;
			w48.Fill = false;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.hseparator1.Hide ();
			this.exportbutton.Hide ();
			this.Show ();
			this.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnKeyPressEvent);
			this.newprevbutton.Clicked += new global::System.EventHandler (this.OnNewBefore);
			this.newafterbutton.Clicked += new global::System.EventHandler (this.OnNewAfter);
			this.newafterbutton.Activated += new global::System.EventHandler (this.OnNewBefore);
			this.removebutton.Clicked += new global::System.EventHandler (this.OnRemove);
			this.editbutton.Clicked += new global::System.EventHandler (this.OnEdit);
			this.exportbutton.Clicked += new global::System.EventHandler (this.OnExportbuttonClicked);
		}
	}
}
