
// This file has been generated by the GUI designer. Do not modify.
namespace LongoMatch.Gui.Component
{
	public partial class ProjectTemplateWidget
	{
		private global::Gtk.HBox hbox1;

		private global::Gtk.ScrolledWindow scrolledwindow2;

		private global::LongoMatch.Gui.Component.CategoriesTreeView sectionstreeview1;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Button newprevbutton;

		private global::Gtk.Button newafterbutton;

		private global::Gtk.Button removebutton;

		private global::Gtk.Button editbutton;

		private global::Gtk.HSeparator hseparator1;

		private global::Gtk.Button exportbutton;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LongoMatch.Gui.Component.ProjectTemplateWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "LongoMatch.Gui.Component.ProjectTemplateWidget";
			// Container child LongoMatch.Gui.Component.ProjectTemplateWidget.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.scrolledwindow2 = new global::Gtk.ScrolledWindow ();
			this.scrolledwindow2.CanFocus = true;
			this.scrolledwindow2.Name = "scrolledwindow2";
			this.scrolledwindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrolledwindow2.Gtk.Container+ContainerChild
			this.sectionstreeview1 = new global::LongoMatch.Gui.Component.CategoriesTreeView ();
			this.sectionstreeview1.CanFocus = true;
			this.sectionstreeview1.Name = "sectionstreeview1";
			this.scrolledwindow2.Add (this.sectionstreeview1);
			this.hbox1.Add (this.scrolledwindow2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.scrolledwindow2]));
			w2.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.newprevbutton = new global::Gtk.Button ();
			this.newprevbutton.TooltipMarkup = "Insert a new category before the selected one";
			this.newprevbutton.Sensitive = false;
			this.newprevbutton.CanFocus = true;
			this.newprevbutton.Name = "newprevbutton";
			this.newprevbutton.UseUnderline = true;
			// Container child newprevbutton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w3 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w4 = new global::Gtk.HBox ();
			w4.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w5 = new global::Gtk.Image ();
			w5.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-goto-top", global::Gtk.IconSize.Menu);
			w4.Add (w5);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w7 = new global::Gtk.Label ();
			w7.LabelProp = global::Mono.Unix.Catalog.GetString ("New Before");
			w7.UseUnderline = true;
			w4.Add (w7);
			w3.Add (w4);
			this.newprevbutton.Add (w3);
			this.vbox2.Add (this.newprevbutton);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.newprevbutton]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.newafterbutton = new global::Gtk.Button ();
			this.newafterbutton.TooltipMarkup = "Insert a new category after the selected one";
			this.newafterbutton.Sensitive = false;
			this.newafterbutton.CanFocus = true;
			this.newafterbutton.Name = "newafterbutton";
			this.newafterbutton.UseUnderline = true;
			// Container child newafterbutton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w12 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w13 = new global::Gtk.HBox ();
			w13.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w14 = new global::Gtk.Image ();
			w14.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-goto-bottom", global::Gtk.IconSize.Menu);
			w13.Add (w14);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w16 = new global::Gtk.Label ();
			w16.LabelProp = global::Mono.Unix.Catalog.GetString ("New After");
			w16.UseUnderline = true;
			w13.Add (w16);
			w12.Add (w13);
			this.newafterbutton.Add (w12);
			this.vbox2.Add (this.newafterbutton);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.newafterbutton]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.removebutton = new global::Gtk.Button ();
			this.removebutton.TooltipMarkup = "Remove the selected category";
			this.removebutton.Sensitive = false;
			this.removebutton.CanFocus = true;
			this.removebutton.Name = "removebutton";
			this.removebutton.UseUnderline = true;
			// Container child removebutton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w21 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w22 = new global::Gtk.HBox ();
			w22.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w23 = new global::Gtk.Image ();
			w23.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-remove", global::Gtk.IconSize.Menu);
			w22.Add (w23);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w25 = new global::Gtk.Label ();
			w25.LabelProp = global::Mono.Unix.Catalog.GetString ("Remove");
			w25.UseUnderline = true;
			w22.Add (w25);
			w21.Add (w22);
			this.removebutton.Add (w21);
			this.vbox2.Add (this.removebutton);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.removebutton]));
			w29.Position = 2;
			w29.Expand = false;
			w29.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.editbutton = new global::Gtk.Button ();
			this.editbutton.TooltipMarkup = "Edit the selected category";
			this.editbutton.Sensitive = false;
			this.editbutton.CanFocus = true;
			this.editbutton.Name = "editbutton";
			this.editbutton.UseUnderline = true;
			// Container child editbutton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w30 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w31 = new global::Gtk.HBox ();
			w31.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w32 = new global::Gtk.Image ();
			w32.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-edit", global::Gtk.IconSize.Menu);
			w31.Add (w32);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w34 = new global::Gtk.Label ();
			w34.LabelProp = global::Mono.Unix.Catalog.GetString ("Edit");
			w34.UseUnderline = true;
			w31.Add (w34);
			w30.Add (w31);
			this.editbutton.Add (w30);
			this.vbox2.Add (this.editbutton);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.editbutton]));
			w38.Position = 3;
			w38.Expand = false;
			w38.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hseparator1 = new global::Gtk.HSeparator ();
			this.hseparator1.Name = "hseparator1";
			this.vbox2.Add (this.hseparator1);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hseparator1]));
			w39.Position = 4;
			w39.Expand = false;
			w39.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.exportbutton = new global::Gtk.Button ();
			this.exportbutton.TooltipMarkup = "Export the template to a file";
			this.exportbutton.CanFocus = true;
			this.exportbutton.Name = "exportbutton";
			this.exportbutton.UseUnderline = true;
			// Container child exportbutton.Gtk.Container+ContainerChild
			global::Gtk.Alignment w40 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w41 = new global::Gtk.HBox ();
			w41.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w42 = new global::Gtk.Image ();
			w42.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-save-as", global::Gtk.IconSize.Menu);
			w41.Add (w42);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w44 = new global::Gtk.Label ();
			w44.LabelProp = global::Mono.Unix.Catalog.GetString ("Export");
			w44.UseUnderline = true;
			w41.Add (w44);
			w40.Add (w41);
			this.exportbutton.Add (w40);
			this.vbox2.Add (this.exportbutton);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.exportbutton]));
			w48.PackType = ((global::Gtk.PackType)(1));
			w48.Position = 5;
			w48.Expand = false;
			w48.Fill = false;
			this.hbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.vbox2]));
			w49.Position = 1;
			w49.Expand = false;
			w49.Fill = false;
			this.Add (this.hbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.hseparator1.Hide ();
			this.exportbutton.Hide ();
			this.Show ();
			this.KeyPressEvent += new global::Gtk.KeyPressEventHandler (this.OnKeyPressEvent);
			this.sectionstreeview1.SectionClicked += new global::LongoMatch.Handlers.SectionHandler (this.OnSectionstreeview1SectionClicked);
			this.sectionstreeview1.SectionsSelected += new global::LongoMatch.Handlers.SectionsHandler (this.OnSectionstreeview1SectionsSelected);
			this.newprevbutton.Clicked += new global::System.EventHandler (this.OnNewBefore);
			this.newafterbutton.Clicked += new global::System.EventHandler (this.OnNewAfter);
			this.newafterbutton.Activated += new global::System.EventHandler (this.OnNewBefore);
			this.removebutton.Clicked += new global::System.EventHandler (this.OnRemove);
			this.editbutton.Clicked += new global::System.EventHandler (this.OnEdit);
			this.exportbutton.Clicked += new global::System.EventHandler (this.OnExportbuttonClicked);
		}
	}
}
