// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LongoMatch {
    
    
    public partial class PrecisionWidget {
        
        private Gtk.VBox vbox2;
        
        private Gtk.HBox hbox1;
        
        private Gtk.Button mbutton;
        
        private Gtk.Button mmbutton;
        
        private Gtk.Button mmmbutton;
        
        private Gtk.HBox hbox2;
        
        private Gtk.Button lbutton;
        
        private Gtk.Button llbutton;
        
        private Gtk.Button lllbutton;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget LongoMatch.PrecisionWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "LongoMatch.PrecisionWidget";
            // Container child LongoMatch.PrecisionWidget.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Homogeneous = true;
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.mbutton = new Gtk.Button();
            this.mbutton.CanFocus = true;
            this.mbutton.Name = "mbutton";
            this.mbutton.UseUnderline = true;
            this.mbutton.Label = "+";
            this.hbox1.Add(this.mbutton);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.hbox1[this.mbutton]));
            w1.Position = 0;
            // Container child hbox1.Gtk.Box+BoxChild
            this.mmbutton = new Gtk.Button();
            this.mmbutton.CanFocus = true;
            this.mmbutton.Name = "mmbutton";
            this.mmbutton.UseUnderline = true;
            this.mmbutton.Label = "++";
            this.hbox1.Add(this.mmbutton);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.hbox1[this.mmbutton]));
            w2.Position = 1;
            // Container child hbox1.Gtk.Box+BoxChild
            this.mmmbutton = new Gtk.Button();
            this.mmmbutton.CanFocus = true;
            this.mmmbutton.Name = "mmmbutton";
            this.mmmbutton.UseUnderline = true;
            this.mmmbutton.Label = "+++";
            this.hbox1.Add(this.mmmbutton);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.hbox1[this.mmmbutton]));
            w3.Position = 2;
            this.vbox2.Add(this.hbox1);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox1]));
            w4.Position = 0;
            w4.Expand = false;
            w4.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Homogeneous = true;
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.lbutton = new Gtk.Button();
            this.lbutton.CanFocus = true;
            this.lbutton.Name = "lbutton";
            this.lbutton.UseUnderline = true;
            this.lbutton.Label = "-";
            this.hbox2.Add(this.lbutton);
            Gtk.Box.BoxChild w5 = ((Gtk.Box.BoxChild)(this.hbox2[this.lbutton]));
            w5.Position = 0;
            // Container child hbox2.Gtk.Box+BoxChild
            this.llbutton = new Gtk.Button();
            this.llbutton.CanFocus = true;
            this.llbutton.Name = "llbutton";
            this.llbutton.UseUnderline = true;
            this.llbutton.Label = "--";
            this.hbox2.Add(this.llbutton);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.hbox2[this.llbutton]));
            w6.Position = 1;
            // Container child hbox2.Gtk.Box+BoxChild
            this.lllbutton = new Gtk.Button();
            this.lllbutton.CanFocus = true;
            this.lllbutton.Name = "lllbutton";
            this.lllbutton.UseUnderline = true;
            this.lllbutton.Label = "---";
            this.hbox2.Add(this.lllbutton);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.hbox2[this.lllbutton]));
            w7.Position = 2;
            this.vbox2.Add(this.hbox2);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox2[this.hbox2]));
            w8.Position = 1;
            w8.Expand = false;
            w8.Fill = false;
            this.Add(this.vbox2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.Show();
            this.mbutton.Clicked += new System.EventHandler(this.OnMbuttonClicked);
            this.mmbutton.Clicked += new System.EventHandler(this.OnMmbuttonClicked);
            this.mmmbutton.Clicked += new System.EventHandler(this.OnMmmbuttonClicked);
            this.lbutton.Clicked += new System.EventHandler(this.OnLbuttonClicked);
            this.llbutton.Clicked += new System.EventHandler(this.OnLlbuttonClicked);
            this.lllbutton.Clicked += new System.EventHandler(this.OnLllbuttonClicked);
        }
    }
}
