// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LongoMatch.Gui.Component {
    
    
    public partial class ProjectDetailsWidget {
        
        private Gtk.VBox vbox2;
        
        private Gtk.Table table1;
        
        private Gtk.Label audiobitratelabel;
        
        private Gtk.SpinButton audiobitratespinbutton;
        
        private Gtk.ComboBox audiodevicecombobox;
        
        private Gtk.Label audiodevicelabel;
        
        private Gtk.Entry competitionentry;
        
        private Gtk.Label Competitionlabel;
        
        private Gtk.HBox filehbox;
        
        private Gtk.Entry fileEntry;
        
        private Gtk.Button openbutton;
        
        private Gtk.Label filelabel;
        
        private Gtk.HBox hbox1;
        
        private Gtk.ComboBox localcombobox;
        
        private Gtk.Button localtemplatebutton;
        
        private Gtk.HBox hbox2;
        
        private Gtk.ComboBox visitorcombobox;
        
        private Gtk.Button visitorbutton;
        
        private Gtk.HBox hbox3;
        
        private Gtk.ComboBox tagscombobox;
        
        private Gtk.Button editbutton;
        
        private Gtk.HBox hbox5;
        
        private Gtk.Entry dateEntry;
        
        private Gtk.Button calendarbutton;
        
        private Gtk.Label label10;
        
        private Gtk.Label label11;
        
        private Gtk.Label label12;
        
        private Gtk.Label label5;
        
        private Gtk.Label label8;
        
        private Gtk.Label label9;
        
        private Gtk.SpinButton localSpinButton;
        
        private Gtk.Entry localTeamEntry;
        
        private Gtk.Label localteamtemplatelabel;
        
        private Gtk.Entry seasonentry;
        
        private Gtk.Label seasonlabel;
        
        private Gtk.Label videobitratelabel1;
        
        private Gtk.SpinButton videobitratespinbutton;
        
        private Gtk.Label videodevice;
        
        private Gtk.ComboBox videodevicecombobox;
        
        private Gtk.SpinButton visitorSpinButton;
        
        private Gtk.Entry visitorTeamEntry;
        
        private Gtk.Label visitorteamtemplatelabel;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget LongoMatch.Gui.Component.ProjectDetailsWidget
            Stetic.BinContainer.Attach(this);
            this.Name = "LongoMatch.Gui.Component.ProjectDetailsWidget";
            // Container child LongoMatch.Gui.Component.ProjectDetailsWidget.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.table1 = new Gtk.Table(((uint)(15)), ((uint)(2)), false);
            this.table1.Name = "table1";
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.audiobitratelabel = new Gtk.Label();
            this.audiobitratelabel.Name = "audiobitratelabel";
            this.audiobitratelabel.LabelProp = Mono.Unix.Catalog.GetString("Audio Bitrate (kbps):");
            this.table1.Add(this.audiobitratelabel);
            Gtk.Table.TableChild w1 = ((Gtk.Table.TableChild)(this.table1[this.audiobitratelabel]));
            w1.TopAttach = ((uint)(14));
            w1.BottomAttach = ((uint)(15));
            w1.XOptions = ((Gtk.AttachOptions)(4));
            w1.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.audiobitratespinbutton = new Gtk.SpinButton(0, 360, 1);
            this.audiobitratespinbutton.CanFocus = true;
            this.audiobitratespinbutton.Name = "audiobitratespinbutton";
            this.audiobitratespinbutton.Adjustment.PageIncrement = 10;
            this.audiobitratespinbutton.ClimbRate = 1;
            this.audiobitratespinbutton.Numeric = true;
            this.audiobitratespinbutton.Value = 64;
            this.table1.Add(this.audiobitratespinbutton);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table1[this.audiobitratespinbutton]));
            w2.TopAttach = ((uint)(14));
            w2.BottomAttach = ((uint)(15));
            w2.LeftAttach = ((uint)(1));
            w2.RightAttach = ((uint)(2));
            w2.XOptions = ((Gtk.AttachOptions)(0));
            w2.YOptions = ((Gtk.AttachOptions)(0));
            // Container child table1.Gtk.Table+TableChild
            this.audiodevicecombobox = Gtk.ComboBox.NewText();
            this.audiodevicecombobox.Name = "audiodevicecombobox";
            this.table1.Add(this.audiodevicecombobox);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.audiodevicecombobox]));
            w3.TopAttach = ((uint)(12));
            w3.BottomAttach = ((uint)(13));
            w3.LeftAttach = ((uint)(1));
            w3.RightAttach = ((uint)(2));
            w3.XOptions = ((Gtk.AttachOptions)(4));
            w3.YOptions = ((Gtk.AttachOptions)(0));
            // Container child table1.Gtk.Table+TableChild
            this.audiodevicelabel = new Gtk.Label();
            this.audiodevicelabel.Name = "audiodevicelabel";
            this.audiodevicelabel.LabelProp = Mono.Unix.Catalog.GetString("Audio Device:");
            this.table1.Add(this.audiodevicelabel);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table1[this.audiodevicelabel]));
            w4.TopAttach = ((uint)(12));
            w4.BottomAttach = ((uint)(13));
            w4.XOptions = ((Gtk.AttachOptions)(4));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.competitionentry = new Gtk.Entry();
            this.competitionentry.CanFocus = true;
            this.competitionentry.Name = "competitionentry";
            this.competitionentry.IsEditable = true;
            this.competitionentry.InvisibleChar = '●';
            this.table1.Add(this.competitionentry);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table1[this.competitionentry]));
            w5.TopAttach = ((uint)(5));
            w5.BottomAttach = ((uint)(6));
            w5.LeftAttach = ((uint)(1));
            w5.RightAttach = ((uint)(2));
            w5.XOptions = ((Gtk.AttachOptions)(4));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.Competitionlabel = new Gtk.Label();
            this.Competitionlabel.Name = "Competitionlabel";
            this.Competitionlabel.LabelProp = Mono.Unix.Catalog.GetString("Competition:");
            this.table1.Add(this.Competitionlabel);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table1[this.Competitionlabel]));
            w6.TopAttach = ((uint)(5));
            w6.BottomAttach = ((uint)(6));
            w6.XOptions = ((Gtk.AttachOptions)(4));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.filehbox = new Gtk.HBox();
            this.filehbox.Name = "filehbox";
            this.filehbox.Spacing = 6;
            // Container child filehbox.Gtk.Box+BoxChild
            this.fileEntry = new Gtk.Entry();
            this.fileEntry.CanFocus = true;
            this.fileEntry.Name = "fileEntry";
            this.fileEntry.IsEditable = false;
            this.fileEntry.InvisibleChar = '●';
            this.filehbox.Add(this.fileEntry);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.filehbox[this.fileEntry]));
            w7.Position = 0;
            // Container child filehbox.Gtk.Box+BoxChild
            this.openbutton = new Gtk.Button();
            this.openbutton.CanFocus = true;
            this.openbutton.Name = "openbutton";
            this.openbutton.UseStock = true;
            this.openbutton.UseUnderline = true;
            this.openbutton.Label = "gtk-open";
            this.filehbox.Add(this.openbutton);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.filehbox[this.openbutton]));
            w8.Position = 1;
            w8.Expand = false;
            this.table1.Add(this.filehbox);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.table1[this.filehbox]));
            w9.TopAttach = ((uint)(10));
            w9.BottomAttach = ((uint)(11));
            w9.LeftAttach = ((uint)(1));
            w9.RightAttach = ((uint)(2));
            w9.XOptions = ((Gtk.AttachOptions)(4));
            w9.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.filelabel = new Gtk.Label();
            this.filelabel.Name = "filelabel";
            this.filelabel.LabelProp = Mono.Unix.Catalog.GetString("File:");
            this.table1.Add(this.filelabel);
            Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.table1[this.filelabel]));
            w10.TopAttach = ((uint)(10));
            w10.BottomAttach = ((uint)(11));
            w10.XOptions = ((Gtk.AttachOptions)(4));
            w10.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.hbox1 = new Gtk.HBox();
            this.hbox1.Name = "hbox1";
            this.hbox1.Spacing = 6;
            // Container child hbox1.Gtk.Box+BoxChild
            this.localcombobox = Gtk.ComboBox.NewText();
            this.localcombobox.Name = "localcombobox";
            this.hbox1.Add(this.localcombobox);
            Gtk.Box.BoxChild w11 = ((Gtk.Box.BoxChild)(this.hbox1[this.localcombobox]));
            w11.Position = 0;
            // Container child hbox1.Gtk.Box+BoxChild
            this.localtemplatebutton = new Gtk.Button();
            this.localtemplatebutton.CanFocus = true;
            this.localtemplatebutton.Name = "localtemplatebutton";
            this.localtemplatebutton.UseStock = true;
            this.localtemplatebutton.UseUnderline = true;
            this.localtemplatebutton.Label = "gtk-edit";
            this.hbox1.Add(this.localtemplatebutton);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.hbox1[this.localtemplatebutton]));
            w12.PackType = ((Gtk.PackType)(1));
            w12.Position = 1;
            w12.Expand = false;
            w12.Fill = false;
            this.table1.Add(this.hbox1);
            Gtk.Table.TableChild w13 = ((Gtk.Table.TableChild)(this.table1[this.hbox1]));
            w13.TopAttach = ((uint)(7));
            w13.BottomAttach = ((uint)(8));
            w13.LeftAttach = ((uint)(1));
            w13.RightAttach = ((uint)(2));
            w13.XOptions = ((Gtk.AttachOptions)(4));
            w13.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.hbox2 = new Gtk.HBox();
            this.hbox2.Name = "hbox2";
            this.hbox2.Spacing = 6;
            // Container child hbox2.Gtk.Box+BoxChild
            this.visitorcombobox = Gtk.ComboBox.NewText();
            this.visitorcombobox.Name = "visitorcombobox";
            this.hbox2.Add(this.visitorcombobox);
            Gtk.Box.BoxChild w14 = ((Gtk.Box.BoxChild)(this.hbox2[this.visitorcombobox]));
            w14.Position = 0;
            // Container child hbox2.Gtk.Box+BoxChild
            this.visitorbutton = new Gtk.Button();
            this.visitorbutton.CanFocus = true;
            this.visitorbutton.Name = "visitorbutton";
            this.visitorbutton.UseStock = true;
            this.visitorbutton.UseUnderline = true;
            this.visitorbutton.Label = "gtk-edit";
            this.hbox2.Add(this.visitorbutton);
            Gtk.Box.BoxChild w15 = ((Gtk.Box.BoxChild)(this.hbox2[this.visitorbutton]));
            w15.PackType = ((Gtk.PackType)(1));
            w15.Position = 1;
            w15.Expand = false;
            w15.Fill = false;
            this.table1.Add(this.hbox2);
            Gtk.Table.TableChild w16 = ((Gtk.Table.TableChild)(this.table1[this.hbox2]));
            w16.TopAttach = ((uint)(8));
            w16.BottomAttach = ((uint)(9));
            w16.LeftAttach = ((uint)(1));
            w16.RightAttach = ((uint)(2));
            w16.XOptions = ((Gtk.AttachOptions)(4));
            w16.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.hbox3 = new Gtk.HBox();
            this.hbox3.Name = "hbox3";
            this.hbox3.Spacing = 6;
            // Container child hbox3.Gtk.Box+BoxChild
            this.tagscombobox = Gtk.ComboBox.NewText();
            this.tagscombobox.Name = "tagscombobox";
            this.hbox3.Add(this.tagscombobox);
            Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.hbox3[this.tagscombobox]));
            w17.Position = 0;
            // Container child hbox3.Gtk.Box+BoxChild
            this.editbutton = new Gtk.Button();
            this.editbutton.CanFocus = true;
            this.editbutton.Name = "editbutton";
            this.editbutton.UseStock = true;
            this.editbutton.UseUnderline = true;
            this.editbutton.Label = "gtk-edit";
            this.hbox3.Add(this.editbutton);
            Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(this.hbox3[this.editbutton]));
            w18.PackType = ((Gtk.PackType)(1));
            w18.Position = 1;
            w18.Expand = false;
            w18.Fill = false;
            this.table1.Add(this.hbox3);
            Gtk.Table.TableChild w19 = ((Gtk.Table.TableChild)(this.table1[this.hbox3]));
            w19.TopAttach = ((uint)(6));
            w19.BottomAttach = ((uint)(7));
            w19.LeftAttach = ((uint)(1));
            w19.RightAttach = ((uint)(2));
            w19.XOptions = ((Gtk.AttachOptions)(4));
            w19.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.hbox5 = new Gtk.HBox();
            this.hbox5.Name = "hbox5";
            // Container child hbox5.Gtk.Box+BoxChild
            this.dateEntry = new Gtk.Entry();
            this.dateEntry.CanFocus = true;
            this.dateEntry.Name = "dateEntry";
            this.dateEntry.IsEditable = false;
            this.dateEntry.InvisibleChar = '●';
            this.hbox5.Add(this.dateEntry);
            Gtk.Box.BoxChild w20 = ((Gtk.Box.BoxChild)(this.hbox5[this.dateEntry]));
            w20.Position = 0;
            // Container child hbox5.Gtk.Box+BoxChild
            this.calendarbutton = new Gtk.Button();
            this.calendarbutton.CanFocus = true;
            this.calendarbutton.Name = "calendarbutton";
            this.calendarbutton.UseUnderline = true;
            // Container child calendarbutton.Gtk.Container+ContainerChild
            Gtk.Alignment w21 = new Gtk.Alignment(0.5F, 0.5F, 0F, 0F);
            // Container child GtkAlignment.Gtk.Container+ContainerChild
            Gtk.HBox w22 = new Gtk.HBox();
            w22.Spacing = 2;
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Image w23 = new Gtk.Image();
            w23.Pixbuf = Stetic.IconLoader.LoadIcon(this, "stock_calendar", Gtk.IconSize.Button, 20);
            w22.Add(w23);
            // Container child GtkHBox.Gtk.Container+ContainerChild
            Gtk.Label w25 = new Gtk.Label();
            w25.LabelProp = Mono.Unix.Catalog.GetString("_Calendar");
            w25.UseUnderline = true;
            w22.Add(w25);
            w21.Add(w22);
            this.calendarbutton.Add(w21);
            this.hbox5.Add(this.calendarbutton);
            Gtk.Box.BoxChild w29 = ((Gtk.Box.BoxChild)(this.hbox5[this.calendarbutton]));
            w29.Position = 1;
            w29.Expand = false;
            w29.Fill = false;
            this.table1.Add(this.hbox5);
            Gtk.Table.TableChild w30 = ((Gtk.Table.TableChild)(this.table1[this.hbox5]));
            w30.TopAttach = ((uint)(9));
            w30.BottomAttach = ((uint)(10));
            w30.LeftAttach = ((uint)(1));
            w30.RightAttach = ((uint)(2));
            w30.YOptions = ((Gtk.AttachOptions)(1));
            // Container child table1.Gtk.Table+TableChild
            this.label10 = new Gtk.Label();
            this.label10.Name = "label10";
            this.label10.LabelProp = Mono.Unix.Catalog.GetString("Visitor Team:");
            this.table1.Add(this.label10);
            Gtk.Table.TableChild w31 = ((Gtk.Table.TableChild)(this.table1[this.label10]));
            w31.TopAttach = ((uint)(1));
            w31.BottomAttach = ((uint)(2));
            w31.XOptions = ((Gtk.AttachOptions)(4));
            w31.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label11 = new Gtk.Label();
            this.label11.Name = "label11";
            this.label11.LabelProp = Mono.Unix.Catalog.GetString("Local Goals:");
            this.table1.Add(this.label11);
            Gtk.Table.TableChild w32 = ((Gtk.Table.TableChild)(this.table1[this.label11]));
            w32.TopAttach = ((uint)(2));
            w32.BottomAttach = ((uint)(3));
            w32.XOptions = ((Gtk.AttachOptions)(4));
            w32.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label12 = new Gtk.Label();
            this.label12.Name = "label12";
            this.label12.LabelProp = Mono.Unix.Catalog.GetString("Visitor Goals:");
            this.table1.Add(this.label12);
            Gtk.Table.TableChild w33 = ((Gtk.Table.TableChild)(this.table1[this.label12]));
            w33.TopAttach = ((uint)(3));
            w33.BottomAttach = ((uint)(4));
            w33.XOptions = ((Gtk.AttachOptions)(4));
            w33.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label5 = new Gtk.Label();
            this.label5.Name = "label5";
            this.label5.LabelProp = Mono.Unix.Catalog.GetString("Date:");
            this.table1.Add(this.label5);
            Gtk.Table.TableChild w34 = ((Gtk.Table.TableChild)(this.table1[this.label5]));
            w34.TopAttach = ((uint)(9));
            w34.BottomAttach = ((uint)(10));
            w34.XOptions = ((Gtk.AttachOptions)(4));
            w34.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label8 = new Gtk.Label();
            this.label8.Name = "label8";
            this.label8.LabelProp = Mono.Unix.Catalog.GetString("Local Team:");
            this.table1.Add(this.label8);
            Gtk.Table.TableChild w35 = ((Gtk.Table.TableChild)(this.table1[this.label8]));
            w35.XOptions = ((Gtk.AttachOptions)(4));
            w35.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label9 = new Gtk.Label();
            this.label9.Name = "label9";
            this.label9.LabelProp = Mono.Unix.Catalog.GetString("Categories Template:");
            this.table1.Add(this.label9);
            Gtk.Table.TableChild w36 = ((Gtk.Table.TableChild)(this.table1[this.label9]));
            w36.TopAttach = ((uint)(6));
            w36.BottomAttach = ((uint)(7));
            w36.XOptions = ((Gtk.AttachOptions)(4));
            w36.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.localSpinButton = new Gtk.SpinButton(0, 1000, 1);
            this.localSpinButton.CanFocus = true;
            this.localSpinButton.Name = "localSpinButton";
            this.localSpinButton.Adjustment.PageIncrement = 10;
            this.localSpinButton.ClimbRate = 1;
            this.localSpinButton.Numeric = true;
            this.table1.Add(this.localSpinButton);
            Gtk.Table.TableChild w37 = ((Gtk.Table.TableChild)(this.table1[this.localSpinButton]));
            w37.TopAttach = ((uint)(2));
            w37.BottomAttach = ((uint)(3));
            w37.LeftAttach = ((uint)(1));
            w37.RightAttach = ((uint)(2));
            w37.XOptions = ((Gtk.AttachOptions)(1));
            w37.YOptions = ((Gtk.AttachOptions)(1));
            // Container child table1.Gtk.Table+TableChild
            this.localTeamEntry = new Gtk.Entry();
            this.localTeamEntry.CanFocus = true;
            this.localTeamEntry.Name = "localTeamEntry";
            this.localTeamEntry.IsEditable = true;
            this.localTeamEntry.InvisibleChar = '●';
            this.table1.Add(this.localTeamEntry);
            Gtk.Table.TableChild w38 = ((Gtk.Table.TableChild)(this.table1[this.localTeamEntry]));
            w38.LeftAttach = ((uint)(1));
            w38.RightAttach = ((uint)(2));
            // Container child table1.Gtk.Table+TableChild
            this.localteamtemplatelabel = new Gtk.Label();
            this.localteamtemplatelabel.Name = "localteamtemplatelabel";
            this.localteamtemplatelabel.LabelProp = Mono.Unix.Catalog.GetString("Visitor Team Template");
            this.table1.Add(this.localteamtemplatelabel);
            Gtk.Table.TableChild w39 = ((Gtk.Table.TableChild)(this.table1[this.localteamtemplatelabel]));
            w39.TopAttach = ((uint)(8));
            w39.BottomAttach = ((uint)(9));
            w39.XOptions = ((Gtk.AttachOptions)(4));
            w39.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.seasonentry = new Gtk.Entry();
            this.seasonentry.CanFocus = true;
            this.seasonentry.Name = "seasonentry";
            this.seasonentry.IsEditable = true;
            this.seasonentry.InvisibleChar = '●';
            this.table1.Add(this.seasonentry);
            Gtk.Table.TableChild w40 = ((Gtk.Table.TableChild)(this.table1[this.seasonentry]));
            w40.TopAttach = ((uint)(4));
            w40.BottomAttach = ((uint)(5));
            w40.LeftAttach = ((uint)(1));
            w40.RightAttach = ((uint)(2));
            w40.XOptions = ((Gtk.AttachOptions)(4));
            w40.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.seasonlabel = new Gtk.Label();
            this.seasonlabel.Name = "seasonlabel";
            this.seasonlabel.LabelProp = Mono.Unix.Catalog.GetString("Season:");
            this.table1.Add(this.seasonlabel);
            Gtk.Table.TableChild w41 = ((Gtk.Table.TableChild)(this.table1[this.seasonlabel]));
            w41.TopAttach = ((uint)(4));
            w41.BottomAttach = ((uint)(5));
            w41.XOptions = ((Gtk.AttachOptions)(4));
            w41.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.videobitratelabel1 = new Gtk.Label();
            this.videobitratelabel1.Name = "videobitratelabel1";
            this.videobitratelabel1.LabelProp = Mono.Unix.Catalog.GetString("Video Bitrate (kbps):");
            this.table1.Add(this.videobitratelabel1);
            Gtk.Table.TableChild w42 = ((Gtk.Table.TableChild)(this.table1[this.videobitratelabel1]));
            w42.TopAttach = ((uint)(13));
            w42.BottomAttach = ((uint)(14));
            w42.XOptions = ((Gtk.AttachOptions)(4));
            w42.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.videobitratespinbutton = new Gtk.SpinButton(1000, 8000, 1);
            this.videobitratespinbutton.CanFocus = true;
            this.videobitratespinbutton.Name = "videobitratespinbutton";
            this.videobitratespinbutton.Adjustment.PageIncrement = 10;
            this.videobitratespinbutton.ClimbRate = 1;
            this.videobitratespinbutton.Numeric = true;
            this.videobitratespinbutton.Value = 4000;
            this.table1.Add(this.videobitratespinbutton);
            Gtk.Table.TableChild w43 = ((Gtk.Table.TableChild)(this.table1[this.videobitratespinbutton]));
            w43.TopAttach = ((uint)(13));
            w43.BottomAttach = ((uint)(14));
            w43.LeftAttach = ((uint)(1));
            w43.RightAttach = ((uint)(2));
            w43.XOptions = ((Gtk.AttachOptions)(0));
            w43.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.videodevice = new Gtk.Label();
            this.videodevice.Name = "videodevice";
            this.videodevice.LabelProp = Mono.Unix.Catalog.GetString("Video Device:");
            this.table1.Add(this.videodevice);
            Gtk.Table.TableChild w44 = ((Gtk.Table.TableChild)(this.table1[this.videodevice]));
            w44.TopAttach = ((uint)(11));
            w44.BottomAttach = ((uint)(12));
            w44.XOptions = ((Gtk.AttachOptions)(4));
            w44.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.videodevicecombobox = Gtk.ComboBox.NewText();
            this.videodevicecombobox.Name = "videodevicecombobox";
            this.table1.Add(this.videodevicecombobox);
            Gtk.Table.TableChild w45 = ((Gtk.Table.TableChild)(this.table1[this.videodevicecombobox]));
            w45.TopAttach = ((uint)(11));
            w45.BottomAttach = ((uint)(12));
            w45.LeftAttach = ((uint)(1));
            w45.RightAttach = ((uint)(2));
            w45.XOptions = ((Gtk.AttachOptions)(4));
            w45.YOptions = ((Gtk.AttachOptions)(0));
            // Container child table1.Gtk.Table+TableChild
            this.visitorSpinButton = new Gtk.SpinButton(0, 1000, 1);
            this.visitorSpinButton.CanFocus = true;
            this.visitorSpinButton.Name = "visitorSpinButton";
            this.visitorSpinButton.Adjustment.PageIncrement = 10;
            this.visitorSpinButton.ClimbRate = 1;
            this.visitorSpinButton.Numeric = true;
            this.table1.Add(this.visitorSpinButton);
            Gtk.Table.TableChild w46 = ((Gtk.Table.TableChild)(this.table1[this.visitorSpinButton]));
            w46.TopAttach = ((uint)(3));
            w46.BottomAttach = ((uint)(4));
            w46.LeftAttach = ((uint)(1));
            w46.RightAttach = ((uint)(2));
            w46.XOptions = ((Gtk.AttachOptions)(1));
            w46.YOptions = ((Gtk.AttachOptions)(1));
            // Container child table1.Gtk.Table+TableChild
            this.visitorTeamEntry = new Gtk.Entry();
            this.visitorTeamEntry.CanFocus = true;
            this.visitorTeamEntry.Name = "visitorTeamEntry";
            this.visitorTeamEntry.IsEditable = true;
            this.visitorTeamEntry.InvisibleChar = '●';
            this.table1.Add(this.visitorTeamEntry);
            Gtk.Table.TableChild w47 = ((Gtk.Table.TableChild)(this.table1[this.visitorTeamEntry]));
            w47.TopAttach = ((uint)(1));
            w47.BottomAttach = ((uint)(2));
            w47.LeftAttach = ((uint)(1));
            w47.RightAttach = ((uint)(2));
            w47.XOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.visitorteamtemplatelabel = new Gtk.Label();
            this.visitorteamtemplatelabel.Name = "visitorteamtemplatelabel";
            this.visitorteamtemplatelabel.LabelProp = Mono.Unix.Catalog.GetString("Local Team Template");
            this.table1.Add(this.visitorteamtemplatelabel);
            Gtk.Table.TableChild w48 = ((Gtk.Table.TableChild)(this.table1[this.visitorteamtemplatelabel]));
            w48.TopAttach = ((uint)(7));
            w48.BottomAttach = ((uint)(8));
            w48.XOptions = ((Gtk.AttachOptions)(4));
            w48.YOptions = ((Gtk.AttachOptions)(4));
            this.vbox2.Add(this.table1);
            Gtk.Box.BoxChild w49 = ((Gtk.Box.BoxChild)(this.vbox2[this.table1]));
            w49.Position = 0;
            this.Add(this.vbox2);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.audiodevicelabel.Hide();
            this.editbutton.Hide();
            this.videobitratelabel1.Hide();
            this.videodevice.Hide();
            this.Show();
            this.visitorTeamEntry.Changed += new System.EventHandler(this.OnEdited);
            this.visitorSpinButton.ValueChanged += new System.EventHandler(this.OnEdited);
            this.seasonentry.Changed += new System.EventHandler(this.OnEdited);
            this.localTeamEntry.Changed += new System.EventHandler(this.OnEdited);
            this.localSpinButton.ValueChanged += new System.EventHandler(this.OnEdited);
            this.dateEntry.Changed += new System.EventHandler(this.OnEdited);
            this.calendarbutton.Clicked += new System.EventHandler(this.OnCalendarbuttonClicked);
            this.tagscombobox.Changed += new System.EventHandler(this.OnCombobox1Changed);
            this.editbutton.Clicked += new System.EventHandler(this.OnEditbuttonClicked);
            this.visitorcombobox.Changed += new System.EventHandler(this.OnVisitorcomboboxChanged);
            this.visitorbutton.Clicked += new System.EventHandler(this.OnVisitorbuttonClicked);
            this.localcombobox.Changed += new System.EventHandler(this.OnLocalcomboboxChanged);
            this.localtemplatebutton.Clicked += new System.EventHandler(this.OnLocaltemplatebuttonClicked);
            this.fileEntry.Changed += new System.EventHandler(this.OnEdited);
            this.openbutton.Clicked += new System.EventHandler(this.OnOpenbuttonClicked);
            this.competitionentry.Changed += new System.EventHandler(this.OnEdited);
        }
    }
}
