// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.42
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LongoMatch {
    
    
    public partial class MainWindow {
        
        private Gtk.VBox vbox1;
        
        private Gtk.VBox menubox;
        
        private Gtk.HPaned hpaned;
        
        private Gtk.VBox leftbox;
        
        private LongoMatch.TreeWidget treewidget1;
        
        private Gtk.HPaned hpaned1;
        
        private Gtk.VBox vbox5;
        
        private CesarPlayer.PlayerBin playerbin1;
        
        private LongoMatch.TimeLine timeline2;
        
        private LongoMatch.ButtonsWidget buttonswidget1;
        
        private LongoMatch.PlayListWidget playlistwidget2;
        
        private Gtk.Statusbar statusbar1;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget LongoMatch.MainWindow
            Gtk.UIManager w1 = new Gtk.UIManager();
            Gtk.ActionGroup w2 = new Gtk.ActionGroup("Default");
            w1.InsertActionGroup(w2, 0);
            this.AddAccelGroup(w1.AccelGroup);
            this.Name = "LongoMatch.MainWindow";
            this.Title = Mono.Unix.Catalog.GetString("LongoMatch");
            this.Icon = new Gdk.Pixbuf(System.IO.Path.Combine(System.AppDomain.CurrentDomain.BaseDirectory, "./bin/Release/logo.png"));
            this.WindowPosition = ((Gtk.WindowPosition)(3));
            this.Gravity = ((Gdk.Gravity)(5));
            // Container child LongoMatch.MainWindow.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            // Container child vbox1.Gtk.Box+BoxChild
            this.menubox = new Gtk.VBox();
            this.menubox.Name = "menubox";
            this.menubox.Spacing = 6;
            this.vbox1.Add(this.menubox);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox1[this.menubox]));
            w3.Position = 0;
            w3.Expand = false;
            w3.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hpaned = new Gtk.HPaned();
            this.hpaned.CanFocus = true;
            this.hpaned.Name = "hpaned";
            this.hpaned.Position = 261;
            // Container child hpaned.Gtk.Paned+PanedChild
            this.leftbox = new Gtk.VBox();
            this.leftbox.Name = "leftbox";
            this.leftbox.Spacing = 6;
            // Container child leftbox.Gtk.Box+BoxChild
            this.treewidget1 = new LongoMatch.TreeWidget();
            this.treewidget1.Events = ((Gdk.EventMask)(256));
            this.treewidget1.Name = "treewidget1";
            this.leftbox.Add(this.treewidget1);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(this.leftbox[this.treewidget1]));
            w4.Position = 0;
            this.hpaned.Add(this.leftbox);
            Gtk.Paned.PanedChild w5 = ((Gtk.Paned.PanedChild)(this.hpaned[this.leftbox]));
            w5.Resize = false;
            // Container child hpaned.Gtk.Paned+PanedChild
            this.hpaned1 = new Gtk.HPaned();
            this.hpaned1.CanFocus = true;
            this.hpaned1.Name = "hpaned1";
            this.hpaned1.Position = 526;
            // Container child hpaned1.Gtk.Paned+PanedChild
            this.vbox5 = new Gtk.VBox();
            this.vbox5.WidthRequest = 320;
            this.vbox5.Name = "vbox5";
            this.vbox5.Spacing = 6;
            // Container child vbox5.Gtk.Box+BoxChild
            this.playerbin1 = new CesarPlayer.PlayerBin();
            this.playerbin1.Events = ((Gdk.EventMask)(256));
            this.playerbin1.Name = "playerbin1";
            this.vbox5.Add(this.playerbin1);
            Gtk.Box.BoxChild w6 = ((Gtk.Box.BoxChild)(this.vbox5[this.playerbin1]));
            w6.Position = 0;
            // Container child vbox5.Gtk.Box+BoxChild
            this.timeline2 = new LongoMatch.TimeLine();
            this.timeline2.Events = ((Gdk.EventMask)(256));
            this.timeline2.Name = "timeline2";
            this.timeline2.Enabled = false;
            this.vbox5.Add(this.timeline2);
            Gtk.Box.BoxChild w7 = ((Gtk.Box.BoxChild)(this.vbox5[this.timeline2]));
            w7.Position = 1;
            w7.Expand = false;
            w7.Fill = false;
            // Container child vbox5.Gtk.Box+BoxChild
            this.buttonswidget1 = new LongoMatch.ButtonsWidget();
            this.buttonswidget1.Events = ((Gdk.EventMask)(256));
            this.buttonswidget1.Name = "buttonswidget1";
            this.vbox5.Add(this.buttonswidget1);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(this.vbox5[this.buttonswidget1]));
            w8.Position = 2;
            w8.Expand = false;
            this.hpaned1.Add(this.vbox5);
            Gtk.Paned.PanedChild w9 = ((Gtk.Paned.PanedChild)(this.hpaned1[this.vbox5]));
            w9.Resize = false;
            w9.Shrink = false;
            // Container child hpaned1.Gtk.Paned+PanedChild
            this.playlistwidget2 = new LongoMatch.PlayListWidget();
            this.playlistwidget2.WidthRequest = 200;
            this.playlistwidget2.Events = ((Gdk.EventMask)(256));
            this.playlistwidget2.Name = "playlistwidget2";
            this.hpaned1.Add(this.playlistwidget2);
            Gtk.Paned.PanedChild w10 = ((Gtk.Paned.PanedChild)(this.hpaned1[this.playlistwidget2]));
            w10.Resize = false;
            w10.Shrink = false;
            this.hpaned.Add(this.hpaned1);
            this.vbox1.Add(this.hpaned);
            Gtk.Box.BoxChild w12 = ((Gtk.Box.BoxChild)(this.vbox1[this.hpaned]));
            w12.Position = 1;
            // Container child vbox1.Gtk.Box+BoxChild
            this.statusbar1 = new Gtk.Statusbar();
            this.statusbar1.Name = "statusbar1";
            this.statusbar1.Spacing = 6;
            this.vbox1.Add(this.statusbar1);
            Gtk.Box.BoxChild w13 = ((Gtk.Box.BoxChild)(this.vbox1[this.statusbar1]));
            w13.Position = 2;
            w13.Expand = false;
            w13.Fill = false;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 1005;
            this.DefaultHeight = 569;
            this.leftbox.Hide();
            this.timeline2.Hide();
            this.buttonswidget1.Hide();
            this.playlistwidget2.Hide();
            this.Show();
            this.DeleteEvent += new Gtk.DeleteEventHandler(this.OnDeleteEvent);
            this.treewidget1.TimeNodeSelected += new LongoMatch.TimeNodeSelectedHandler(this.OnTimeNodeSelected);
            this.treewidget1.TimeNodeChanged += new LongoMatch.TimeNodeChangedHandler(this.OnTimeNodeChanged);
            this.treewidget1.TimeNodeDeleted += new LongoMatch.TimeNodeDeletedHandler(this.OnTimeNodeDeleted);
            this.treewidget1.PlayListNodeAdded += new LongoMatch.PlayListNodeAddedHandler(this.OnPlayListNodeAdded);
            this.playerbin1.TickEvent += new CesarPlayer.TickEventHandler(this.OnPlayerbin1TickEvent);
            this.playerbin1.SegmentClosedEvent += new CesarPlayer.SegmentClosedHandler(this.OnPlayerbin1SegmentClosedEvent);
            this.playerbin1.ErrorEvent += new CesarPlayer.ErrorEventHandler(this.OnPlayerbin1ErrorEvent);
            this.timeline2.TimeNodeChanged += new LongoMatch.TimeNodeChangedHandler(this.OnTimeScaleTimeNodeChanged);
            this.timeline2.PositionChanged += new LongoMatch.PositionChangedHandler(this.OnTimeline2PositionChanged);
            this.buttonswidget1.NewMarkEvent += new LongoMatch.NewMarkEventHandler(this.OnNewMark);
            this.playlistwidget2.PlayListNodeSelected += new LongoMatch.PlayListNodeSelectedHandler(this.OnPlaylistwidget2PlayListNodeSelected);
        }
    }
}
