// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LongoMatch.Gui.Dialog {
    
    
    public partial class TeamTemplateEditor {
        
        private LongoMatch.Gui.Component.TeamTemplateWidget teamtemplatewidget1;
        
        private Gtk.Button buttonOk;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget LongoMatch.Gui.Dialog.TeamTemplateEditor
            this.Name = "LongoMatch.Gui.Dialog.TeamTemplateEditor";
            this.Icon = Gdk.Pixbuf.LoadFromResource("longomatch.png");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.Modal = true;
            this.Gravity = ((Gdk.Gravity)(5));
            this.SkipPagerHint = true;
            this.SkipTaskbarHint = true;
            // Internal child LongoMatch.Gui.Dialog.TeamTemplateEditor.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.teamtemplatewidget1 = new LongoMatch.Gui.Component.TeamTemplateWidget();
            this.teamtemplatewidget1.Events = ((Gdk.EventMask)(256));
            this.teamtemplatewidget1.Name = "teamtemplatewidget1";
            this.teamtemplatewidget1.Edited = false;
            w1.Add(this.teamtemplatewidget1);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(w1[this.teamtemplatewidget1]));
            w2.Position = 0;
            // Internal child LongoMatch.Gui.Dialog.TeamTemplateEditor.ActionArea
            Gtk.HButtonBox w3 = this.ActionArea;
            w3.Name = "dialog1_ActionArea";
            w3.Spacing = 6;
            w3.BorderWidth = ((uint)(5));
            w3.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonOk = new Gtk.Button();
            this.buttonOk.CanDefault = true;
            this.buttonOk.CanFocus = true;
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.UseStock = true;
            this.buttonOk.UseUnderline = true;
            this.buttonOk.Label = "gtk-apply";
            this.AddActionWidget(this.buttonOk, -10);
            Gtk.ButtonBox.ButtonBoxChild w4 = ((Gtk.ButtonBox.ButtonBoxChild)(w3[this.buttonOk]));
            w4.Expand = false;
            w4.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 436;
            this.DefaultHeight = 313;
            this.Show();
        }
    }
}
