// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LongoMatch.Gui.Dialog {
    
    
    public partial class FramesCaptureProgressDialog {
        
        private Gtk.VBox vbox2;
        
        private Gtk.ProgressBar progressbar;
        
        private Gtk.Image image;
        
        private Gtk.Button okbutton;
        
        private Gtk.Button cancelbutton;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget LongoMatch.Gui.Dialog.FramesCaptureProgressDialog
            this.Name = "LongoMatch.Gui.Dialog.FramesCaptureProgressDialog";
            this.Title = Mono.Unix.Catalog.GetString("Capture Progress");
            this.Icon = Stetic.IconLoader.LoadIcon(this, "longomatch", Gtk.IconSize.Dialog, 48);
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.Modal = true;
            this.BorderWidth = ((uint)(3));
            this.Resizable = false;
            this.AllowGrow = false;
            this.Gravity = ((Gdk.Gravity)(5));
            this.SkipPagerHint = true;
            this.SkipTaskbarHint = true;
            // Internal child LongoMatch.Gui.Dialog.FramesCaptureProgressDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.progressbar = new Gtk.ProgressBar();
            this.progressbar.Name = "progressbar";
            this.vbox2.Add(this.progressbar);
            Gtk.Box.BoxChild w2 = ((Gtk.Box.BoxChild)(this.vbox2[this.progressbar]));
            w2.Position = 0;
            w2.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.image = new Gtk.Image();
            this.image.Name = "image";
            this.vbox2.Add(this.image);
            Gtk.Box.BoxChild w3 = ((Gtk.Box.BoxChild)(this.vbox2[this.image]));
            w3.PackType = ((Gtk.PackType)(1));
            w3.Position = 1;
            w1.Add(this.vbox2);
            Gtk.Box.BoxChild w4 = ((Gtk.Box.BoxChild)(w1[this.vbox2]));
            w4.Position = 0;
            // Internal child LongoMatch.Gui.Dialog.FramesCaptureProgressDialog.ActionArea
            Gtk.HButtonBox w5 = this.ActionArea;
            w5.Name = "dialog1_ActionArea";
            w5.Spacing = 6;
            w5.BorderWidth = ((uint)(5));
            w5.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.okbutton = new Gtk.Button();
            this.okbutton.CanFocus = true;
            this.okbutton.Name = "okbutton";
            this.okbutton.UseStock = true;
            this.okbutton.UseUnderline = true;
            this.okbutton.Label = "gtk-ok";
            this.AddActionWidget(this.okbutton, -5);
            Gtk.ButtonBox.ButtonBoxChild w6 = ((Gtk.ButtonBox.ButtonBoxChild)(w5[this.okbutton]));
            w6.Expand = false;
            w6.Fill = false;
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.cancelbutton = new Gtk.Button();
            this.cancelbutton.CanDefault = true;
            this.cancelbutton.CanFocus = true;
            this.cancelbutton.Name = "cancelbutton";
            this.cancelbutton.UseStock = true;
            this.cancelbutton.UseUnderline = true;
            this.cancelbutton.Label = "gtk-cancel";
            this.AddActionWidget(this.cancelbutton, -6);
            Gtk.ButtonBox.ButtonBoxChild w7 = ((Gtk.ButtonBox.ButtonBoxChild)(w5[this.cancelbutton]));
            w7.Position = 1;
            w7.Expand = false;
            w7.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 400;
            this.DefaultHeight = 130;
            this.okbutton.Hide();
            this.Show();
            this.cancelbutton.Clicked += new System.EventHandler(this.OnButtonCancelClicked);
        }
    }
}
