// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace LongoMatch.Gui.Dialog {
    
    
    public partial class EntryDialog {
        
        private Gtk.Table table1;
        
        private Gtk.CheckButton checkbutton;
        
        private Gtk.Entry entry1;
        
        private Gtk.Label existentemplatelabel;
        
        private Gtk.Label label2;
        
        private Gtk.Label playerslabel;
        
        private Gtk.SpinButton playersspinbutton;
        
        private Gtk.ComboBox combobox;
        
        private Gtk.Button buttonCancel;
        
        private Gtk.Button buttonOk;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget LongoMatch.Gui.Dialog.EntryDialog
            this.Name = "LongoMatch.Gui.Dialog.EntryDialog";
            this.Title = Mono.Unix.Catalog.GetString("Select template name");
            this.Icon = Stetic.IconLoader.LoadIcon(this, "longomatch", Gtk.IconSize.Dialog, 48);
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            this.Modal = true;
            this.Gravity = ((Gdk.Gravity)(5));
            this.SkipPagerHint = true;
            this.SkipTaskbarHint = true;
            // Internal child LongoMatch.Gui.Dialog.EntryDialog.VBox
            Gtk.VBox w1 = this.VBox;
            w1.Name = "dialog1_VBox";
            w1.BorderWidth = ((uint)(2));
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.table1 = new Gtk.Table(((uint)(3)), ((uint)(2)), false);
            this.table1.RowSpacing = ((uint)(6));
            this.table1.ColumnSpacing = ((uint)(6));
            // Container child table1.Gtk.Table+TableChild
            this.checkbutton = new Gtk.CheckButton();
            this.checkbutton.CanFocus = true;
            this.checkbutton.Name = "checkbutton";
            this.checkbutton.Label = "";
            this.checkbutton.DrawIndicator = true;
            this.checkbutton.UseUnderline = true;
            this.table1.Add(this.checkbutton);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.table1[this.checkbutton]));
            w2.TopAttach = ((uint)(2));
            w2.BottomAttach = ((uint)(3));
            w2.LeftAttach = ((uint)(1));
            w2.RightAttach = ((uint)(2));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.entry1 = new Gtk.Entry();
            this.entry1.CanFocus = true;
            this.entry1.Name = "entry1";
            this.entry1.IsEditable = true;
            this.entry1.InvisibleChar = '●';
            this.table1.Add(this.entry1);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.table1[this.entry1]));
            w3.LeftAttach = ((uint)(1));
            w3.RightAttach = ((uint)(2));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.existentemplatelabel = new Gtk.Label();
            this.existentemplatelabel.Name = "existentemplatelabel";
            this.existentemplatelabel.LabelProp = Mono.Unix.Catalog.GetString("Copy existent template:");
            this.table1.Add(this.existentemplatelabel);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.table1[this.existentemplatelabel]));
            w4.TopAttach = ((uint)(2));
            w4.BottomAttach = ((uint)(3));
            w4.XOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.Xalign = 0F;
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("Name:");
            this.table1.Add(this.label2);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.table1[this.label2]));
            w5.XOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.playerslabel = new Gtk.Label();
            this.playerslabel.Name = "playerslabel";
            this.playerslabel.Xalign = 0F;
            this.playerslabel.LabelProp = Mono.Unix.Catalog.GetString("Players:");
            this.table1.Add(this.playerslabel);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.table1[this.playerslabel]));
            w6.TopAttach = ((uint)(1));
            w6.BottomAttach = ((uint)(2));
            w6.XOptions = ((Gtk.AttachOptions)(4));
            // Container child table1.Gtk.Table+TableChild
            this.playersspinbutton = new Gtk.SpinButton(1, 100, 1);
            this.playersspinbutton.CanFocus = true;
            this.playersspinbutton.Name = "playersspinbutton";
            this.playersspinbutton.Adjustment.PageIncrement = 10;
            this.playersspinbutton.ClimbRate = 1;
            this.playersspinbutton.Numeric = true;
            this.playersspinbutton.Value = 15;
            this.table1.Add(this.playersspinbutton);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.table1[this.playersspinbutton]));
            w7.TopAttach = ((uint)(1));
            w7.BottomAttach = ((uint)(2));
            w7.LeftAttach = ((uint)(1));
            w7.RightAttach = ((uint)(2));
            w7.XOptions = ((Gtk.AttachOptions)(4));
            w7.YOptions = ((Gtk.AttachOptions)(0));
            w1.Add(this.table1);
            Gtk.Box.BoxChild w8 = ((Gtk.Box.BoxChild)(w1[this.table1]));
            w8.Position = 0;
            // Container child dialog1_VBox.Gtk.Box+BoxChild
            this.combobox = Gtk.ComboBox.NewText();
            this.combobox.Sensitive = false;
            this.combobox.Name = "combobox";
            w1.Add(this.combobox);
            Gtk.Box.BoxChild w9 = ((Gtk.Box.BoxChild)(w1[this.combobox]));
            w9.Position = 1;
            w9.Expand = false;
            w9.Fill = false;
            // Internal child LongoMatch.Gui.Dialog.EntryDialog.ActionArea
            Gtk.HButtonBox w10 = this.ActionArea;
            w10.Name = "dialog1_ActionArea";
            w10.Spacing = 6;
            w10.BorderWidth = ((uint)(5));
            w10.LayoutStyle = ((Gtk.ButtonBoxStyle)(4));
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonCancel = new Gtk.Button();
            this.buttonCancel.CanDefault = true;
            this.buttonCancel.CanFocus = true;
            this.buttonCancel.Name = "buttonCancel";
            this.buttonCancel.UseStock = true;
            this.buttonCancel.UseUnderline = true;
            this.buttonCancel.Label = "gtk-cancel";
            this.AddActionWidget(this.buttonCancel, -6);
            Gtk.ButtonBox.ButtonBoxChild w11 = ((Gtk.ButtonBox.ButtonBoxChild)(w10[this.buttonCancel]));
            w11.Expand = false;
            w11.Fill = false;
            // Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
            this.buttonOk = new Gtk.Button();
            this.buttonOk.CanDefault = true;
            this.buttonOk.CanFocus = true;
            this.buttonOk.Name = "buttonOk";
            this.buttonOk.UseStock = true;
            this.buttonOk.UseUnderline = true;
            this.buttonOk.Label = "gtk-ok";
            this.AddActionWidget(this.buttonOk, -5);
            Gtk.ButtonBox.ButtonBoxChild w12 = ((Gtk.ButtonBox.ButtonBoxChild)(w10[this.buttonOk]));
            w12.Position = 1;
            w12.Expand = false;
            w12.Fill = false;
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 339;
            this.DefaultHeight = 178;
            this.Show();
            this.checkbutton.Toggled += new System.EventHandler(this.OnCheckbuttonToggled);
        }
    }
}
