
// This file has been generated by the GUI designer. Do not modify.
namespace LongoMatch.Gui.Component
{
	public partial class PlayersTaggerWidget
	{
		private global::Gtk.Frame frame1;

		private global::Gtk.Alignment GtkAlignment;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label label2;

		private global::Gtk.Label playerslabel;

		private global::Gtk.Button button5;

		private global::Gtk.Label CategoryLabel;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LongoMatch.Gui.Component.PlayersTaggerWidget
			global::Stetic.BinContainer.Attach (this);
			this.Name = "LongoMatch.Gui.Component.PlayersTaggerWidget";
			// Container child LongoMatch.Gui.Component.PlayersTaggerWidget.Gtk.Container+ContainerChild
			this.frame1 = new global::Gtk.Frame ();
			this.frame1.Name = "frame1";
			this.frame1.ShadowType = ((global::Gtk.ShadowType)(2));
			// Container child frame1.Gtk.Container+ContainerChild
			this.GtkAlignment = new global::Gtk.Alignment (0f, 0f, 1f, 1f);
			this.GtkAlignment.Name = "GtkAlignment";
			this.GtkAlignment.LeftPadding = ((uint)(12));
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 0f;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Players:");
			this.hbox1.Add (this.label2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label2]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.playerslabel = new global::Gtk.Label ();
			this.playerslabel.Name = "playerslabel";
			this.playerslabel.Xalign = 0f;
			this.playerslabel.LabelProp = global::Mono.Unix.Catalog.GetString ("None");
			this.hbox1.Add (this.playerslabel);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.playerslabel]));
			w2.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button5 = new global::Gtk.Button ();
			this.button5.CanFocus = true;
			this.button5.Name = "button5";
			this.button5.UseStock = true;
			this.button5.UseUnderline = true;
			this.button5.Label = "gtk-edit";
			this.hbox1.Add (this.button5);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button5]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			this.GtkAlignment.Add (this.hbox1);
			this.frame1.Add (this.GtkAlignment);
			this.CategoryLabel = new global::Gtk.Label ();
			this.CategoryLabel.Name = "CategoryLabel";
			this.CategoryLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("<b>GtkFrame</b>");
			this.CategoryLabel.UseMarkup = true;
			this.frame1.LabelWidget = this.CategoryLabel;
			this.Add (this.frame1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
		}
	}
}
